### PR TITLE
Tidy up Dockerfile somewhat

### PR DESCRIPTION
**Pull request by dracos**
Remove some unneeded bits, use the scripts again now they're updated for jessie, other bits and bobs. (Not sure if you preferred jessie or trusty, it's easy to have either.) The output can be seen at https://hub.docker.com/r/dracos/mapit/

I guess really the database should be its own container, presumably using https://hub.docker.com/r/mdillon/postgis/ which might make things simpler/smaller.

### CODE REVIEW

**Comment by MTRNord** [comment]
I will use some of the things. But I switched to my own mapit fork (because I can make there an clean mapit_de) so the local install script will be used.

**Comment by MTRNord** [comment]
I merged the things that are still needed to the Repo manually :) See:  cb0d50828d760abeb94c393ca7c568a92d0558e4

**Comment by dracos** [comment]
Whilst I understand you create a fork of mapit to add/test your `mapit_de`, I highly recommend and ask that you do so without deleting everything existing in it, so that you can feed your changes back upstream and can more easily pull in updates from upstream. e.g. looking at https://github.com/Nordgedanken/mapit/commit/3d39c659835c0f8c36de003dbce1becc938b4b58 or https://github.com/Nordgedanken/mapit/commit/0abab6247adc40d200b16a3b1d9f7ecebec2a0fd please don't delete lots of existing code, please add your own on top of what's there. Otherwise you will find it hard to keep up to date as other changes are made to MapIt in future.

**Comment by MTRNord** [comment]
I didn't thaught about that. I will revert the deletions :) Thanks for the Info

**Pull request closed without merging**
